-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jun 10, 2024 at 02:06 PM
-- Server version: 8.0.30
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pw2024_tubes_233040007`
--

-- --------------------------------------------------------

--
-- Table structure for table `tb_admin`
--

CREATE TABLE `tb_admin` (
  `admin_id` int NOT NULL,
  `admin_name` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `admin_telp` varchar(20) NOT NULL,
  `admin_email` varchar(50) NOT NULL,
  `admin_address` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `tb_admin`
--

INSERT INTO `tb_admin` (`admin_id`, `admin_name`, `username`, `password`, `admin_telp`, `admin_email`, `admin_address`) VALUES
(1, 'Rival Anugrah Azi Febrian', 'admin', '199fe4d8efc7cbfb42d40124ca03cc19', '+6283898545962', 'rivalanugrah4@gmail.com', 'Indramayu Anjatan');

-- --------------------------------------------------------

--
-- Table structure for table `tb_category`
--

CREATE TABLE `tb_category` (
  `category_id` int NOT NULL,
  `category_name` varchar(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `tb_category`
--

INSERT INTO `tb_category` (`category_id`, `category_name`) VALUES
(3, 'Sepatu Bola'),
(4, 'Sepatu Futsal'),
(6, 'Sepatu Ruunning');

-- --------------------------------------------------------

--
-- Table structure for table `tb_product`
--

CREATE TABLE `tb_product` (
  `product_id` int NOT NULL,
  `category_id` int NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `product_price` int NOT NULL,
  `product_description` text NOT NULL,
  `product_image` varchar(100) NOT NULL,
  `product_status` tinyint(1) NOT NULL,
  `date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `tb_product`
--

INSERT INTO `tb_product` (`product_id`, `category_id`, `product_name`, `product_price`, `product_description`, `product_image`, `product_status`, `date_created`) VALUES
(6, 3, 'Specs Sepatu Sepak bola Accelerator Illuzion 3 Elite Fg Black Goniochrome SPE101943', 475000, '<p>Generasi ketiga dari keluarga Illuzion dengan upper ringan, kombinasi dari collar knitting untuk fit yang sempurna, penggabungan mesh, lining berlubang dan lapisan tanpa jahitan yang menghasilkan sepatu speed dengan tampilan sleek. Tambahan grafis tonal yang terinspirasi dari ilusi optik, sempurna untuk pemain yang bergerak sangat cepat untuk menciptakan ilusi.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>The 3rd generation of Illuzion famlly featuring lightweight upper, a combination of knitted collar for excellent fitting, a blend of mesh, perforated lining and no sew overlay, resulting a sleek looking speed boots. Additional subtle graphic taking inspiration from optical illuzion. a perfect for those who moves fast enough to create an illuzion.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>UPPER :No Sew mix with Hi quality knit and Mesh</p>\r\n\r\n<p>SOCKLINER : Molded Eva for cushion,fit and comfort</p>\r\n\r\n<p>OUTSOLE :Accelerator Split sole TPU with Blade stud for maximum traxion</p>\r\n\r\n<p>CONSTRUCTION : Semi Bootie construction with lace</p>\r\n', 'produk1717418853.jpeg', 1, '2024-06-02 15:34:02'),
(7, 4, 'Specs Sepatu Sepak Bola Xlr Fg Crushed Velvet Black SPE102182', 315000, '<p>XLR adalah Sepatu varian kecepatan Accelerator core paling clean, Menggunakan material PU Synthetic non woven backer yang ringan dan mempunyai daya tahan tinggi. Ditambah lagi dengan upper yang clean dan fokus pada tekstur material dan logo brand yang tegas. Dilengkapi dengan Hexa Speed Plate khas Accelerator core untuk pengenalan pada kecepatan.</p>\r\n', 'produk1717419080.jpeg', 1, '2024-06-02 15:34:23'),
(8, 3, 'Specs Sepatu Sepak Bola Lightspeed Reborn Fg Safety Yellow Crescent Green SPE1010090', 599000, '<p>Bagian dari Illuminate pack- Dipersembahkan dengan warna terbaru, Lightspeed reborn yang legendaris dipasarkan kembali dengan material microfiber ringan dan cetak grafis kecepatan cahaya dengan warna Safety Yellow Crescent Green seperti ketika dirilis pertama kali dan dilengkapi dengan outsole dual density khas Specs Accelerator dengan stud anak panah sempurna untuk akselerasi dibalut dengan lapisan iridiscent yang memukau</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>UPPER : Lightweight Microfiber syntetic upper with hi quality print</p>\r\n\r\n<p>INSOLE : die cut EVA Sockliner with textile cover for dry &amp; fit feeling</p>\r\n\r\n<p>OUTSOLE : Accelerator TPU Outsole with Balde Studs for maximum traxion</p>\r\n\r\n<p>OTHERS : Conventional 1 piece upper</p>\r\n', 'produk1717418691.jpeg', 1, '2024-06-02 15:34:43'),
(10, 3, 'Specs Sepatu Sepak Bola Hyperspeed 3 Fg-Ocean Air SPE1010032', 490000, '<p>&nbsp;</p>\r\n\r\n<p>Generasi ketiga dari Hyperspeed ini hadir dengan silhouette dan collar raw edge yang ikonik. Dengan Upper PU Synthetic microfiber backer favorit untuk kenyamanan berakselerasi.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Dibalut dengan grafis yang terinspirasi dari tenun ikat ganda khas Gringsing ,Bali sebagai generasi baru dari Accelerator etnis. Dilengkapi dengan outsole TPU Exospeed khas Lightspeed dengan stud mata anak panah untuk akselerasi maksimal.</p>\r\n', 'produk1717417858.jpeg', 1, '2024-06-02 15:35:22'),
(11, 4, 'Specs Sepatu Futsal Ls Spectra In White Desire Blue Patina Green SPE1020079', 599000, '<p>Melanjutkan generasi LS yang terinspirasi dari Lightspeed reborn,desain LS Mirage fokus pada pesona grafis&nbsp; yang menyerupai texture dengan pilihan warna yang mencolok., representasi dari bias cahaya yang menimbulkan ilusi. Diaplikasikan pada silhouette yang konvensional yang sederhana dan mudah break in. Seri LS kini lebih segar dengan outsole rubber dan&nbsp; IP Midsole&nbsp; yang lebih baru khas Accelerator.</p>\r\n', 'produk1717418080.jpeg', 1, '2024-06-02 15:35:43'),
(12, 4, 'Specs Sepatu Futsal Hyperspeed 3 In-Black SPE1020030', 494000, '<p>Generasi ketiga dari Hyperspeed ini hadir dengan silhouette dan collar raw edge yang ikonik. Dengan Upper PU Synthetic microfiber backer favorit untuk kenyamanan berakselerasi.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Dibalut dengan grafis yang terinspirasi dari tenun ikat ganda khas Gringsing ,Bali sebagai generasi baru dari Accelerator etnis. Dilengkapi dengan outsole TPU Exospeed khas Lightspeed dengan stud mata anak panah untuk akselerasi maksimal.</p>\r\n', 'produk1717418202.jpeg', 1, '2024-06-02 15:36:04'),
(13, 4, 'specs Sepatu Futsal Reacto Hydra Ss Pro In Mysterious Shocking Pink SPE1020020', 480000, '<p>Hadir pada tier PRO, Hydra SS PRO Mengambil analogi proses bergantinya kulit pada ular atau shed skin, Hydra SS mengalami beberapa perubahan radikal, yaitu konstruksi upper di area eyestay, desain tongue dan juga skeleton lining di area collar. Visualisasi shed skin juga ditingkatkan dengan penambahan grafis kulit ular pada area upper dan juga pada TPU Outsole. Hydra SS dilengkapi dengan outsole rubber favorit Specs yang dirancang untuk bobot yang ringan dan ball touch maksima</p>\r\n', 'produk1717418397.jpeg', 1, '2024-06-02 15:36:23'),
(14, 4, 'Specs Sepatu Futsal Accelerator Lightspeed 4 Elite In Flint Gray Neon Aqua SPE110200044', 764000, '<p>Dominasi lightspeed 4 berlanjut dengan ubahan material dan grafis untuk tampilan lebih sleek dan minimalis. Lightspeed 4 Elite disajikan dengan konsep upper yang inovatif, kombinasi Speed bar, desain lapisan TPU tipis exo skeleton, dengan ThermaSkin, Lapisan PU Synthetic Microfiber backer tipis yang signifikan untuk mengurangi bobot tanpa mengorbankan aspek durabilitas. Hadir dengan Rubber outsole dengan IP Midsole khas Accelerator Elite.</p>\r\n', 'produk1717418560.jpeg', 1, '2024-06-02 15:36:43'),
(21, 4, 'Specs Sepatu Futsal Gravity In Wattle Splash Black SPE402318', 314000, '<p>Pilihan warna terbaru dari Gravity FH23 dengan desain dekorasi jahitan yang sleek dan logo yang tegas . Varian ignite pack Reacto ini menggunakan PU Syntetic ringan namun berdaya tahan tinggi dengan non woven backer. Dilengkapi dengan outsole khas Reacto Core.</p>\r\n', 'produk1717419439.jpeg', 1, '2024-06-03 05:57:19'),
(22, 4, 'Specs Sepatu Futsal Xcells In Seed Pearl Mint Leave SPE1020066', 359000, '<p>memperkenalkan varian baru reacto core, xcells yang terinspirasi dari motif turing yang menggambarkan bagaimana pola di alam, seperti garis dan bintik, dapat muncul secara alami dan mandiri dari keadaan yang homogen dan seragam representasi dari keunikan jati diri manusia. Diaplikasikan pada silhouette sepatu konvensional dengan estetika minimalis dengan konstruksi upper 1 bagian dan ooutsole rubber.</p>\r\n', 'produk1717419579.jpeg', 1, '2024-06-03 05:59:39'),
(23, 3, 'Specs Sepatu Sepak Bola Accelerator Speedkraft Core Fg Black Tango Red SPE1010047', 449000, '<p>Accelerator Speedkraft Core, opsi Speedkraft untuk entry level dan youth, dengan estetika yang identik dengan versi Elite nya.&nbsp;Dirancang dengan konsep retro futuristic, melalui penggunaan kombinasi upper 1 bagian PU Synthetic non woven backer dan Hadir dengan outsole TPU Hexaspeed khas accelerator core. 2</p>\r\n', 'produk1717419803.jpeg', 1, '2024-06-03 06:03:23'),
(24, 6, 'Specs Sepatu Running Vortex Sv Subs1 Maui Blue Pink White SPE1040002', 629000, '<p>Memperkenalkan Vortex SV Subs 1, dirancang untuk menaklukkan jarak tempuh dengan pengalaman fitting yang nyaman dengan Gusseted Tongue. Dibuat dengan mesh ultra-breathable di bagian atas, sepatu ini menjaga kaki Anda tetap sejuk dan kering saat Anda berusaha sekuat tenaga. Teknologi bantalan midsole Substance 1 menawarkan keseimbangan sempurna antara bantalan dan pengembalian energi yang responsif, memastikan setiap langkah mendorong Anda maju dengan mudah.</p>\r\n', 'produk1717420746.jpeg', 1, '2024-06-03 06:14:49'),
(25, 6, 'Specs Tempo India Ink Egret Doeskin SPE1000003', 494000, '<p>Tempo adalah proyek spin off pada kategori lifestyle yang terinspirasi dari kategori running, menggunakan desain upper yang klasik dan logo victory bow ternama pada outsole running. Menghasilkan kombinasi sempurna untuk gaya hidup aktif yang serba cepat.</p>\r\n', 'produk1717420865.jpeg', 1, '2024-06-03 06:21:05'),
(26, 6, 'Specs 303_Earthover Forged Iron Pearl City SPE1000006', 494000, '<p>303_Earthover adalah silhouette terbaru dari Specs 1980 di 2024 yang dirancang khusus untuk para petualang yang gemar bermain di alam bebas. Dipersembahkan dengan pattern overlay ikonik yang terinspirasi dari bebatuan terjal, detail webbing khas pendaki, dan juga detail carabiner loop seandainya dibutuhkan. Dengan material yang breathable dan desain lugs rubber outsole yang off road inspired 303_Earthover siap menjadi teman perjalananmu saat ingin menghilang diluar jangkauan</p>\r\n', 'produk1717420985.jpeg', 1, '2024-06-03 06:23:05'),
(27, 4, 'FORTE METEOR IN PISTACHIO PEACH', 479000, '<p>FORTE METEOR IN merupakan versi sepatu Futsal dari FORTE yang bisa Anda temukan di kategori sepatu Futsal. Didesain untuk memberikan performa maksimal saat bermain, sepatu ini dilengkapi dengan teknologi Quick Fit pada bagian upper yang memudahkan Anda untuk menggunakannya dengan cepat. Ditambah lagi, midsole menggunakan teknologi Cumulus foam dan Ortshox yang memberikan kenyamanan maksimal saat berada di lapangan. Sementara itu, outsole dilengkapi dengan teknologi OrtCurve untuk memberikan traksi dan stabilitas yang optimal. Dibuat dengan material upper PU yang tahan lama, midsole menggunakan material Inj. Phylon yang ringan, dan outsole dengan kekerasan rubber 55. Dapatkan sepatu FORTE METEOR IN dan naikkan performa Anda di lapangan Futsal.</p>\r\n', 'produk1717910554.jpg', 1, '2024-06-08 22:15:39'),
(28, 4, 'CATALYST WEAVE IN AQUA WHITE', 399000, '<p>Berikan yang terbaik dengan Catalyst Weave IN, sepatu futsal yang dilengkapi dengan teknologi QuickFit pada bagian upper yang merupakan material lembut pelapis dalam sepatu agar fitting sepatu pas dan langsung mengikuti bentuk kaki. OrtShox yang mengikuti kontur telapak kaki dan mencegah kaki bergeser ketika berlatih. Serta CumulusFoam yang berbahan Injection Phylon yang sangat empuk sekaligus ringan dan berfungsi meredam benturan yang dapat membuat cedera lutut. Sementara pada bagian upper dibuat dari bahanPU Synthetic , Inj. Phylon pada bagian midsole serta rubber hardness 55 pada bagian outsole.</p>\r\n', 'produk1717910696.jpg', 1, '2024-06-08 22:24:56'),
(29, 4, 'MEMPHIS IN PISTACHIO TEAL HONEY', 379000, '<p>Memphis IN adalah versi sepatu futsal yang eksklusif dari brand terkenal, Memphis. Sepatu ini juga tersedia dalam kategori sepak bola. Dengan teknologi Quick Fit pada bagian upper, sepatu ini memberikan kenyamanan dan kecepatan saat digunakan. Midsole dengan teknologi Ortshox memberikan perlindungan dan stabilitas ekstra pada kaki saat bermain futsal. Outsole dengan teknologi OrtCurve memberikan traksi sempurna untuk gerakan yang cepat dan akurat. Sepatu ini terbuat dari bahan upper berkualitas tinggi, yaitu PU syntetic, dan outsole dengan kekerasan karet 55.</p>\r\n', 'produk1717910830.png', 1, '2024-06-08 22:27:10'),
(30, 4, 'FORTE METEOR IN WHITE ORTRED', 479000, '<p>FORTE METEOR IN merupakan versi sepatu Futsal dari FORTE yang bisa Anda temukan di kategori sepatu Futsal. Didesain untuk memberikan performa maksimal saat bermain, sepatu ini dilengkapi dengan teknologi Quick Fit pada bagian upper yang memudahkan Anda untuk menggunakannya dengan cepat. Ditambah lagi, midsole menggunakan teknologi Cumulus foam dan Ortshox yang memberikan kenyamanan maksimal saat berada di lapangan. Sementara itu, outsole dilengkapi dengan teknologi OrtCurve untuk memberikan traksi dan stabilitas yang optimal. Dibuat dengan material upper PU yang tahan lama, midsole menggunakan material Inj. Phylon yang ringan, dan outsole dengan kekerasan rubber 55.</p>\r\n', 'produk1717911011.png', 1, '2024-06-08 22:30:11'),
(31, 4, 'FORTE SAVAGE V3 IN AQUAMARINE BLACK', 529000, '<p>FORTE SAVAGE V3 IN adalah sepatu futsal dari seri FORTE SAVAGE V3 yang dirancang khusus untuk meningkatkan kekuatan Anda dalam bermain. Merupakan seri ketiga dari FORTE SAVAGE V3, sepatu ini menawarkan kualitas dan performa terbaik. Dengan tiga pilihan warna yang menarik, FORTE SAVAGE V3 IN memberikan pilihan gaya yang sesuai dengan preferensi Anda. Dibuat menggunakan material upper Full Grain Leather + PU yang tahan lama. Untuk kenyamanan dan performa maksimal, FORTE SAVAGE V3 IN dilengkapi dengan midsole Injection Phylon yang responsif. Teknologi Cumulus Foam dan Ortshox pada midsole memberikan pelindungan yang maksimal. Outsole sepatu ini menggunakan rubber hardness 55 yang memberikan daya cengkram yang luar biasa di lapangan futsal. Dengan teknologi OrtCurve pada outsole, sepatu ini memberikan stabilitas dan kelincahan saat bergerak di lapangan.Tak hanya itu, FORTE SAVAGE V3 IN juga dilengkapi dengan teknologi Quick Fit pada upper, yang memungkinkan penyesuaian cepat dan presisi pada kaki Anda.</p>\r\n', 'produk1717911125.png', 1, '2024-06-08 22:32:05'),
(32, 4, 'CATALYST VISION V4 IN K-LEA ORTRED', 699000, '<p>Produk CATALYST VISION V4 IN K-LEA Ortred adalah sepatu futsal yang merupakan versi terbaru dari Catalyst Vision. Sepatu ini hadir dalam kategori sepatu futsal dan juga tersedia dalam kategori sepak bola. Dengan fitur-fitur yang luar biasa, sepatu ini dirancang untuk memberikan kenyamanan dan performa yang optimal. Teknologi Quick Fit pada bagian upper memudahkan penggunaan sepatu dengan cepat dan mudah. Midsole sepatu dilengkapi dengan teknologi cumulus foam, memberikan dukungan dan kenyamanan saat bermain futsal. Outsole sepatu ini menggunakan teknologi OrtCurve yang memberikan ketahanan dan daya cengkeram yang baik saat bergerak di lapangan futsal. Dengan kata lain, pemain futsal akan dapat mengoptimalkan performa mereka ketika bermain. Dalam hal material, upper sepatu ini terbuat dari kombinasi bahan K-Lea, mesh, dan PU Nosew yang memberikan kenyamanan terbaik saat digunakan. Midsole sepatu menggunakan bahan Injection Phylon untuk memberikan empuk dan nyaman pada kaki. Sementara itu, outsole menggunakan bahan Rubber dengan tingkat kekerasan 55 yang sangat tahan lama. Dengan desain yang menarik dan fitur-fitur unggulan, CATALYST VISION V4 IN K-LEA Ortred adalah pilihan yang sempurna untuk para pecinta futsal yang ingin tampil dengan maksimal di atas lapangan.</p>\r\n', 'produk1717911292.png', 1, '2024-06-08 22:34:52'),
(33, 4, 'JOGOSALA VICTUS WHITE GREEN', 529000, '<p>Jogosala Victus, sepatu dengan teknologi QuickFit yang cepat menyesuaikan ke bentuk kaki dan OrtForce yang berupa pengaplikasian tekstur pada area tendang untuk grip dan kontrol bola yang presisi sekaligus memberi power pada tiap gerak tendangan. Pada bagian midsole terdapat teknologi CumulusFoam dan OrtShox yang desainnya mengikuti bentuk telapak kaki dan memberi cengkraman sekaligus kenyamanan menapak. serta OrtCurve yang berbentuk lengkung kurva pada tepian bagian outsole. Material upper berupa Full Grain Leather, split suede, PU dan Sandwich Mesh serta inj. Phylon pada midsole ditutup oleh rubber hardness 55 pada bagian outsole.</p>\r\n', 'produk1717911426.png', 1, '2024-06-08 22:37:06'),
(34, 6, 'HYPERBLAST 1.3 WHITE LIME', 599000, '<p>Hyperblast 1.3 adalah sepatu lari kategori running yang merupakan versi terbaru dari Hyperblast. Didesain khusus untuk para pelari yang mengutamakan kenyamanan dan performa saat berlari. Teknologi Ortflow yang terdapat pada bagian upper memberikan sirkulasi udara yang optimal untuk menjaga kestabilan suhu kaki dan mencegah kelembapan. Sementara teknologi Cumulus foam dan Ortshox pada bagian midsole memberikan perlindungan tambahan dari dampak saat berlari, sehingga mengurangi risiko cedera pada kaki dan persendian. Hyperblast 1.3 menggunakan material JSandwich mesh dan PU Nosew pada bagian upper, memberikan kesejukan dan ketahanan tinggi tanpa mengorbankan kenyamanan. Midsole terbuat dari compression Phylon untuk memberikan stabilitas pada setiap langkah Anda. Outsole terbuat dari karet dengan kekerasan 55, memberikan cengkeraman yang baik pada berbagai jenis permukaan. Dengan Hyperblast 1.3, Anda akan merasakan sensasi berlari yang nyaman, stabil, dan terlindungi. Jadilah pelari terbaik dengan Hyperblast 1.3!</p>\r\n', 'produk1717911794.jpg', 1, '2024-06-08 22:41:17'),
(35, 6, 'HYPERGLIDE 1.4 WHITE CYAN BLACK', 599000, '<p>HYPERGLIDE 1.4 sepatu lari terbaru dalam kategori sepatu Running. Produk ini merupakan versi sepatu Running dari seri HYPERGLIDE yang telah terbukti kualitasnya. Dibuat dengan teknologi canggih, HYPERGLIDE 1.4 menawarkan performa luar biasa yang akan meningkatkan pengalaman lari Anda. Fitur-fitur seperti Ortflow, Ortstrap, midsole Cumulus foam, dan Ortshox pada bagian upper, dirancang untuk memberikan kenyamanan dan fleksibilitas maksimal saat Anda berlari. HYPERGLIDE 1.4 menggunakan material terbaik untuk memberikan kualitas yang tak tertandingi. Material upper terbuat dari Mono mesh, PU Nosew, dan PU Synt, memberikan sirkulasi udara optimal dan menjaga kaki Anda kering saat berlari. Midsole HYPERGLIDE 1.4 menggunakan Compression Phylon yang memberikan perlindungan ekstra untuk kaki Anda, mengurangi dampak saat berlari. Sementara itu, outsole terbuat dari bahan Rubber Hardness 55, memberikan daya cengkeram yang kuat sehingga Anda dapat berlari dengan stabil di berbagai jenis permukaan. Dapatkan pengalaman lari yang luar biasa dengan HYPERGLIDE 1.4, sepatu lari yang dirancang khusus untuk meningkatkan performa Anda.</p>\r\n', 'produk1717911927.jpg', 1, '2024-06-08 22:45:27'),
(36, 6, 'HYPERFUSE 1.4 CYAN PUMPKIN', 599000, '<p>HYPERFUSE 1.4 dirancang untuk memberikan pengalaman lari yang halus dan mendukung jarak tempuh yang lebih jauh. Dengan fokus pada penyerapan goncangan dan jarak lari yang lebih panjang, sepatu ini dilengkapi dengan Cushion Midsole yang membuat Anda dapat berlari dengan nyaman dalam waktu yang lebih lama. Beratnya hanya 250 gram, memberikan rasa ringan saat melangkah. Dengan heel to toe sebesar 6 mm, Heel stack 30,5 mm dan fore foot stack sebesar 24,5 mm, sepatu ini memberikan bantalan optimal yang lembut. Didesain untuk kestabilan netral, HYPERFUSE 1.4 cocok untuk Easy Run, Recovery Run, Tempo Run bahkan Long Run. Bagian atas sepatu menggunakan teknologi Ortflow, bahan Jaquards mesh, PU Nosew untuk kenyamanan dan sirkulasi udara yang baik. Midsole sepatu terbuat dari Cumulus OAM dan Ortshox untuk penyerapan goncangan yang lebih baik. Material midsole Compression Phylon memberikan bantalan tambahan, sementara material outsole karet memberikan daya cengkeram yang baik di berbagai jenis permukaan. Tersedia dalam 3 pilihan warna, HYPERFUSE 1.4 adalah teman sempurna bagi para pelari yang mencari pengalaman yang halus dan nyaman, memberikan kemudahan dalam melangkah dengan jarak yang lebih jauh.</p>\r\n', 'produk1717912045.png', 1, '2024-06-08 22:47:25'),
(37, 6, 'HYPERDRIVE 2.1 BLUE TOSCA WHITE', 649000, '<p>HYPERDRIVE 2.1 merupakan updgrade dari seri sebelumya dirancang untuk memberikan pengalaman lari yang ringan dan cepat. Dengan kata kunciRAPID FIRE, sepatu ini memiliki karakteristik, ringan, dan responsif untuk meningkatkan kecepatan Anda. Heel to toe 6 mm, Heel stack 29,5 mm dan Fore Foot stack 19,5 mm, sepatu ini memberikan bantalan yang responsif. Didesain untuk kestabilan yang netral, HYPERDRIVE 2.1 cocok untuk latihan dan perlombaan. Perlombaan yang direkomendasikan mencakup jarak 5-10 K, sedangkan untuk latihan mencakup tempo run, threshold run, interval run, fartlek, dan hill sprint. Bagian atas sepatu menggunakan teknologi Ortflow dan Ortstrap, dengan bahan Mono mesh, PU Nosew, Synt. &amp; Suede, memberikan kenyamanan dan sirkulasi udara yang baik. Midsole sepatu terbuat dari busa Cumulus dan Ortshox untuk responsivitas yang lebih baik. Material midsole Injection Phylon memberikan bantalan yang responsif, sementara material outsole karet memberikan daya cengkeram yang baik di berbagai jenis permukaan. Tersedia dalam 3 pilihan warna, HYPERDRIVE 2.1 adalah pilihan yang tepat bagi para pelari yang mencari pengalaman lari yang ringan dan cepat. Sepatu ini memberikan responsivitas yang tinggi sehingga Anda dapat mencapai kecepatan tinggi dalam setiap langkah.</p>\r\n', 'produk1717912228.jpg', 1, '2024-06-08 22:49:19'),
(38, 6, 'HYPERGLIDE 1.4 ELECTRICITY NAVY ORTRANGE', 599000, '<p>HYPERGLIDE 1.4 sepatu lari terbaru dalam kategori sepatu Running. Produk ini merupakan versi sepatu Running dari seri HYPERGLIDE yang telah terbukti kualitasnya. Dibuat dengan teknologi canggih, HYPERGLIDE 1.4 menawarkan performa luar biasa yang akan meningkatkan pengalaman lari Anda. Fitur-fitur seperti Ortflow, Ortstrap, midsole Cumulus foam, dan Ortshox pada bagian upper, dirancang untuk memberikan kenyamanan dan fleksibilitas maksimal saat Anda berlari. HYPERGLIDE 1.4 menggunakan material terbaik untuk memberikan kualitas yang tak tertandingi. Material upper terbuat dari Mono mesh, PU Nosew, dan PU Synt, memberikan sirkulasi udara optimal dan menjaga kaki Anda kering saat berlari. Midsole HYPERGLIDE 1.4 menggunakan Compression Phylon yang memberikan perlindungan ekstra untuk kaki Anda, mengurangi dampak saat berlari. Sementara itu, outsole terbuat dari bahan Rubber Hardness 55, memberikan daya cengkeram yang kuat sehingga Anda dapat berlari dengan stabil di berbagai jenis permukaan. Dapatkan pengalaman lari yang luar biasa dengan HYPERGLIDE 1.4, sepatu lari yang dirancang khusus untuk meningkatkan performa Anda.</p>\r\n', 'produk1717912642.png', 1, '2024-06-08 22:57:22'),
(39, 6, 'HYPERDRIVE 2.1 ORTRANGE WHITE', 649000, '<p>HYPERDRIVE 2.1 merupakan updgrade dari seri sebelumya dirancang untuk memberikan pengalaman lari yang ringan dan cepat. Dengan kata kunciRAPID FIRE, sepatu ini memiliki karakteristik, ringan, dan responsif untuk meningkatkan kecepatan Anda. Heel to toe 6 mm, Heel stack 29,5 mm dan Fore Foot stack 19,5 mm, sepatu ini memberikan bantalan yang responsif. Didesain untuk kestabilan yang netral, HYPERDRIVE 2.1 cocok untuk latihan dan perlombaan. Perlombaan yang direkomendasikan mencakup jarak 5-10 K, sedangkan untuk latihan mencakup tempo run, threshold run, interval run, fartlek, dan hill sprint. Bagian atas sepatu menggunakan teknologi Ortflow dan Ortstrap, dengan bahan Mono mesh, PU Nosew, Synt. &amp; Suede, memberikan kenyamanan dan sirkulasi udara yang baik. Midsole sepatu terbuat dari busa Cumulus dan Ortshox untuk responsivitas yang lebih baik. Material midsole Injection Phylon memberikan bantalan yang responsif, sementara material outsole karet memberikan daya cengkeram yang baik di berbagai jenis permukaan.</p>\r\n', 'produk1717912822.png', 1, '2024-06-08 23:00:22'),
(40, 3, 'FORTE CLAWS FG CLOUD BLUE', 599000, '<p>Forte Claws FG sepatu sepakbola dengan teknologi QuickFit yang cepat menyesuaikan ke bentuk kaki dan OrtKnit yang bermaterialkan rajutan upper yang lentur sekaligus lembut, berventilasi dengan sirkulasi maksimal. Midsole yang menggunakan grip OrtShox yang mencegah kaki bergeser dan outsole OrtTrex, sistem pul/stud dengan bentuk bilah khusus dan OrtSpine yang menyerupai tulang belakang tubuh manusia dan berfungsi sebagai penopang utama yang menjaga rigiditas. Material upper dari bahan knitting dan PU ditutup dengan bahan outsole dari TPU.</p>\r\n', 'produk1717912967.jpg', 1, '2024-06-08 23:02:47'),
(41, 3, 'ZENITH FG WHITE GOLD', 299000, '<p>Sepatu Zenith FG, sepatu bola yang hadir dibuat khusus untuk kamu yang membutuhkan sepatu yang ringan dengan desain yang atraktif. Sepatu ini dbuat dengan desain yang nyaman dan responsif untuk pemakai nya karena adanya teknologi Quick Fit dan Ortshox dibagian upper dan insole. Dibagian outsole dibuat menggunakan teknologi Ottrex dan Ortspine yang membuat sepatu ini memiliki daya cengkram yang kuat dan dapat melindungi kaki dari cedera. Dilengkapi dengan material PU Syntetic dan TPU di bagian Outsole makin membuat sepatu ini memiliki daya tarik tersendiri.</p>\r\n', 'produk1717913082.jpg', 1, '2024-06-08 23:04:42'),
(42, 3, 'CATALYST WEAVE FG AQUA WHITE', 399000, '<p>Jadilah bintang dilapangan dengan Catalyst Weave FG sepatu berteknologi Quick Fit pada bagian upper yang merupakan maerial lembut pelapis dalam sepatu agar fitting sepatu pas dan langsung mengikuti bentuk kaki. Dibekali pula oleh OrtShox pada bagian midsole yang memberikan grip yang baik dari kaki ke tapak dalam sepatu, serta teknologi OrtTrex dan OrtSpine pada bagian outsole yang berperan penting karena sistem pul/stud menyerupai bentuk bilah sistematis dan penopang utama untuk menjaga rigiditas area belakang dan tengah sepatu. Sepatu ini juga dilengkapi dengan material PU Syntetic pada bagian upper dan TPU pada bagian outsole.</p>\r\n', 'produk1717913183.jpg', 1, '2024-06-08 23:06:23'),
(43, 3, 'CATALYST LEGION V4 FG CLOUD BLUE ULTRA CYAN', 649000, '<p>Catalyst Legion V4 menonjolkan ciri khasnya yang ringan dengan berat hanya 155 gram, sehingga memungkinkan pemain tetap cepat dan lincah dalam permainan. Tersedia dalam tiga pilihan warna yang menarik. Sepatu ini menggunakan material upper PU synthetic microfiber yang berkualitas tinggi dengan teknologi Quick Fit dan Ortstrap pada upper, Outsole sepakbola Catalyst Legion V4 menggunakan teknologi Ortrex dan Ortspine, memberikan daya cengkeram yang kuat dan stabilitas optimal saat melakukan gerakan cepat dan akselerasi. Dengan tagline produk &quot;Feather Lightning Strike&quot;, sepatu ini merupakan pilihan tepat bagi pemain yang menginginkan kekuatan, kecepatan, dan presisi dalam setiap langkahnya.</p>\r\n', 'produk1717913381.jpg', 1, '2024-06-08 23:09:41'),
(44, 3, 'CATALYST LIBERTE V3 FG CYAN GREEN', 599000, '<p>CATALYST LIBERTE V3 FG, seri ketiga dari silo CATALYST LIBERTE, adalah pilihan sempurna bagi mereka yang menginginkan kekuatan maksimal di lapangan dengan outsole yang dirancang khusus untuk firm ground. CATALYST LIBERTE V3 FG menawarkan kombinasi yang luar biasa antara performa dan kekuatan dengan desain silo yang fokus pada kecepatan. Sepatu ini memiliki tiga pilihan warna yang menarik, memastikan Anda tampil stylish di lapangan. Dibuat menggunakan material upper Quick Fit, Ortknit, Ortstrap yang berkualitas tinggi. Outsole dari sepatu ini menggunakan material Orttrex,Ortspine memberikan stabilitas dan daya cengkeram yang optimal di lapangan firm ground.</p>\r\n', 'produk1717913491.png', 1, '2024-06-08 23:11:31'),
(45, 3, 'QUADRA FG WHITE BLACK', 399000, '<p>Tak ragu lagi dalam setiap pertandingan dengan Quadra FG, sepatu dengan teknologi Quick Fit pada bagian upper yang merupakan material lembut pelapis dalam sepatu agar fitting sepatu pas dan langsung mengikuti bentuk kaki. Dibekali pula oleh OrtShox pada bagian midsole yang memberikan grip yang baik dari kaki ke tapak dalam sepatu, serta teknologi OrtTrex dan OrtSpine pada bagian outsole yang berperan penting karena sistem pul/stud menyerupai bentuk bilah sistematis dan penopang utama untuk menjaga rigiditas area belakang dan tengah sepatu. Sepatu ini juga dilengkapi dengan material PU Syntetic pada bagian upper dan TPU pada bagian outsole.</p>\r\n', 'produk1717913651.jpg', 1, '2024-06-08 23:14:11'),
(46, 4, 'MILLS Sepatu Futsal Troya Chaos IN Magenta / LT. Blue / White 9402007', 499000, '<p>MILLS - TROYA CHAOS ACTIVATE THE WARRIOR SENSE WITH MILLS TROYA CHAOS! DOMINATE EVERY MINUTE OF YOUR GAME WITH TROYA TROYA CHAOS! Sepatu Futsal pertama dari MILLS siap menggebrak! MILLS Troya Chaos akan menjadi pembuka dari karya-karya MILLS Football selanjutnya. Datang dengan identitas terbaru dari MILLS Footwear, Warrior Stripe, Troya siap menjadi senjata para pemakainya untuk semakin dominan dan eye-catching di lapangan. Sistem stud pada Troya hadir dengan teknologi HDT-R / High Density Traction Rubber yang membuat kaki Anda akan memiliki daya cengkram, dengan, memiliki abrasi yang baik dan non marking / tidak meninggalkan bekas. Didukung dengan upper bermateri Mills Exoskin Material upper berteknologi yang elastis sintetik yang ringan dan kuat akan mendukung mobilitas tinggi para pemakainya di lapangan. Cocok bagi kamu para speedster yang mendominasi permainan dengan kecepatan tinggi.</p>\r\n', 'produk1717914581.jpeg', 1, '2024-06-08 23:29:41'),
(47, 4, 'MILLS Sepatu Futsal Troya Chaos Turf White / Black / Magenta 9001101', 499000, '<p>MILLS Sepatu Futsal Xyclops Troya Chaos Turf Category : Soccer IN Dirancang untuk Bermain bola diatas rumput sintetis intesitas. Untuk pemain yang ingin menaikan level kecepatan dan kontrol atas bola. Direkomendasikan untuk mini soccer atau training session di rumput berkarakter padat atau keras. MILLS ACG ACTIVE TOUCH adalah teknologi upper sepatu dengan merekayasa tekstur material sehingga menciptakan permukaan matrial yang dapat membantu mencengkram bola untuk menambah power, mengontrol dan mengatur arah bola. MILLS EXOSKIN adalah teknologi upper sepatu sintetik yang ringan, kuat, dan dapat memeluk / memberikan proteksi pada kaki secara maksimal. didesain untuk pemain yang memiliki mobilitas yang tinggi. MILLS HDT-R / High Density Traction Rubber adalah teknologi outsole berbahan campuran karet murni dan bahan kimia sehingga menghasilkan outsole yang dapat mencengram dengan, memiliki abrasi yang baik dan tidak meninggalkan bekas (non marking).</p>\r\n', 'produk1717914682.jpeg', 1, '2024-06-08 23:31:22'),
(48, 4, 'MILLS Sepatu Futsal Troya Chaos IN Purple / Lt. Tosca 9402002', 469000, '<p>MILLS - TROYA CHAOS ACTIVATE THE WARRIOR SENSE WITH MILLS TROYA CHAOS! DOMINATE EVERY MINUTE OF YOUR GAME WITH TROYA TROYA CHAOS! Sepatu Futsal pertama dari MILLS siap menggebrak! MILLS Troya Chaos akan menjadi pembuka dari karya-karya MILLS Football selanjutnya. Datang dengan identitas terbaru dari MILLS Footwear, Warrior Stripe, Troya siap menjadi senjata para pemakainya untuk semakin dominan dan eye-catching di lapangan. Sistem stud pada Troya hadir dengan teknologi HDT-R / High Density Traction Rubber yang membuat kaki Anda akan memiliki daya cengkram, dengan, memiliki abrasi yang baik dan non marking / tidak meninggalkan bekas. Didukung dengan upper bermateri Mills Exoskin Material upper berteknologi yang elastis sintetik yang ringan dan kuat akan mendukung mobilitas tinggi para pemakainya di lapangan. Cocok bagi kamu para speedster yang mendominasi permainan dengan kecepatan tinggi.</p>\r\n', 'produk1717914789.jpeg', 1, '2024-06-08 23:33:09'),
(49, 4, 'MILLS Sepatu Futsal Xyclops Kaldera IN DK. Grey / Black / Gold 9400610', 599000, '<p>&nbsp;</p>\r\n\r\n<p>XYCLOPS KALDERA: FEEL THE HEAT AROUND YOUR FEET! 🌋 Terinspirasi dari pola Kaldera pada jersey pre-match timnas.indonesia, Xyclops Kaldera kini hadir dengan kombinasi warna yang lebih segar dan tak kalah menarik. Cepat, ringan, dan nyaman siap menunjang performamu di atas lapangan hijau. Nano-knit dipadukan dengan Seam Press Skin menghasilkan upper yang ringan, fleksibilitas yang baik, dan fitting yang terbaik di kelasnya.</p>\r\n', 'produk1717914899.jpeg', 1, '2024-06-08 23:34:59'),
(50, 4, 'MILLS Sepatu Futsal Troya Chaos Turf Tosca / Magenta / White 9001102', 499000, '<p>&nbsp;</p>\r\n\r\n<p>MILLS Sepatu Futsal Xyclops Troya Chaos Turf Category : Soccer IN Dirancang untuk Bermain bola diatas rumput sintetis intesitas. Untuk pemain yang ingin menaikan level kecepatan dan kontrol atas bola. Direkomendasikan untuk mini soccer atau training session di rumput berkarakter padat atau keras. MILLS ACG ACTIVE TOUCH adalah teknologi upper sepatu dengan merekayasa tekstur material sehingga menciptakan permukaan matrial yang dapat membantu mencengkram bola untuk menambah power, mengontrol dan mengatur arah bola. MILLS EXOSKIN adalah teknologi upper sepatu sintetik yang ringan, kuat, dan dapat memeluk / memberikan proteksi pada kaki secara maksimal. didesain untuk pemain yang memiliki mobilitas yang tinggi. MILLS HDT-R / High Density Traction Rubber adalah teknologi outsole berbahan campuran karet murni dan bahan kimia sehingga menghasilkan outsole yang dapat mencengram dengan, memiliki abrasi yang baik dan tidak meninggalkan bekas (non marking).</p>\r\n', 'produk1717915001.jpeg', 1, '2024-06-08 23:36:41'),
(51, 4, 'MILLS Sepatu Futsal Dellas IN Black. Iris / Blue / White 9400554', 329000, '<p>Dellas IN , sepatu Futsal terbaru dari MILLS yang siap menemani para football enthusiast menyalurkan hobi bermain Futsal dengan penuh percaya diri dengan performa terbaik bersama DELLAS IN. Desain unik dengan pilihan warna menarik, membuat rasa percaya diri semakin meningkat.</p>\r\n', 'produk1717915101.jpeg', 1, '2024-06-08 23:38:21'),
(52, 3, 'ILLS Sepatu Sepakbola Servius FG Navy / Neon Green 9300703', 329000, '<p>MILLS - SERVIUS Datang dengan identitas terbaru dari MILLS Footwear, Warrior Stripe, Servius siap menjadi senjata para pemakainya untuk semakin dominan dan eye-catching di lapangan. Sistem stud pada Troya hadir dengan teknologi TRX GRVTY+ yang membuat kaki Anda akan memiliki daya cengkram maksimal karena diletakkan pada titik traksi yang sesuai. Didukung dengan upper bermateri Mills Exoskin Material upper berteknologi yang elastis sintetik yang ringan dan kuat akan mendukung mobilitas tinggi para pemakainya di lapangan. Cocok bagi kamu para speedster yang mendominasi permainan dengan kecepatan tinggi.</p>\r\n', 'produk1717915289.jpeg', 1, '2024-06-08 23:41:29'),
(53, 3, 'MILLS Sepatu Sepakbola Troya+ FG Black / Warmred 9300108', 284000, '<p>MILLS - TROYA+ ACTIVATE THE WARRIOR SENSE WITH MILLS TROYA! DOMINATE EVERY MINUTE OF YOUR GAME WITH TROYA! Get that Warrior-Sense back with MILLS Troya+ FG‼️ Troya kembali hadir dengan variasi warna yang berbeda! Paduan warna gelap dan terang dalam satu sepatu, membuat Anda tampil jauh lebih eyecatching. Sistem stud pada Troya hadir dengan teknologi HDT-R / High Density Traction Rubber yang membuat kaki Anda akan memiliki daya cengkram, dengan, memiliki abrasi yang baik dan non marking / tidak meninggalkan bekas. Didukung dengan upper bermateri Mills Exoskin Material upper berteknologi yang elastis sintetik yang ringan dan kuat akan mendukung mobilitas tinggi para pemakainya di lapangan. Cocok bagi kamu para speedster yang mendominasi permainan dengan kecepatan tinggi.</p>\r\n', 'produk1717915390.jpeg', 1, '2024-06-08 23:43:10'),
(54, 3, 'MILLS Sepatu Sepakbola Xenon FG White / Turquoise 9302304', 399000, '<p>Xenon FG, sepatu sepak bola terbaru dari MILLS yang siap menemani para football enthusiast menyalurkan hobi bermain sepak bola. Desain unik dengan pilihan warna menarik, membuat rasa percaya diri semakin meningkat.</p>\r\n', 'produk1717915501.jpeg', 1, '2024-06-08 23:45:01'),
(55, 3, 'MILLS Sepatu Sepakbola Triton Genome Elite FG White / Ocean Blue / Pink 9303004', 899000, '<p>MILLS Sepatu Sepakbola Triton Genome Elite FG Category : Soccer FG Designed to offer ultimate precision and power: Triton Genome Elite 🎯 Nyaman, responsif, dan presisi. Tiga kata yang mewakili Triton Genome Elite yang diciptakan bagi para pemain dengan visi dan akurasi tingkat tinggi! Di lengkapi dengan Teknologi : MILLS NANO KNIT adalah inovasi teknologi upper sepatu knitting yang di desain secara khusus untuk kebutuhan performance. Di program secara khusus untuk mengatur tingkat elastisitas dan serikulasi udara. MILLS SEAMPRESS SKIN adalah teknologi yang membuat konstruksi / dekorasi sepatu tanpa jahitan. Berbahan dasar TPU yang kuat dan ringan. MILLS MUTANPANEL adalah teknologi panel sintetik yang di letakan di area titik tendang dan control sehingga membantu pemain dalam meningkatkan level power, akurasi pada tendangan dan passing.</p>\r\n', 'produk1717915603.jpeg', 1, '2024-06-08 23:46:43'),
(56, 3, 'MILLS Sepatu Sepakbola Troya+ FG Black / Neon 9300107', 379000, '<p>MILLS - TROYA+ Get that Warrior-Sense back with MILLS Troya+ FG‼️ Troya kembali hadir dengan variasi warna yang berbeda! Paduan warna gelap dan terang dalam satu sepatu, membuat Anda tampil jauh lebih eyecatching. Datang dengan identitas terbaru dari MILLS Footwear, Warrior Stripe, Troya siap menjadi senjata para pemakainya untuk semakin dominan dan eye-catching di lapangan. Sistem stud pada Troya hadir dengan teknologi HDT-R / High Density Traction Rubber yang membuat kaki Anda akan memiliki daya cengkram, dengan, memiliki abrasi yang baik dan non marking / tidak meninggalkan bekas. Didukung dengan upper bermateri Mills Exoskin Material upper berteknologi yang elastis sintetik yang ringan dan kuat akan mendukung mobilitas tinggi para pemakainya di lapangan. Cocok bagi kamu para speedster yang mendominasi permainan dengan kecepatan tinggi.</p>\r\n', 'produk1717915715.jpeg', 1, '2024-06-08 23:48:35'),
(57, 3, 'MILLS Sepatu Sepak Bola Vulcan FG Magenta / Black / Neon 9300305', 299000, '<p>MILLS Sepatu Sepak Bola Vulcan FG Sepatu Bola terbaru dari Mills yang di rancang untuk bermain bola &plusmn; 2 Jam, di lapangan dengan karakter padat ( FG ) Direkomendasikan untuk pemain yang versatile dan suka mengandalkan kecepatan. Di lengkapi dengan Teknologi : MILLS EXOSKIN adalah teknologi upper sepatu sintetik yang ringan, kuat, dan dapat memeluk / memberikan proteksi pada kaki secara maksimal. didesain untuk pemain yang memiliki mobilitas yang tinggi. MILLS LITE COMFORT adalah teknologi insole sepatu berbahas dasar molded EVA yang ringan. dideasain untuk memberikan kenyamanan maksimal. Teknologi insole ini juga disertai lapisan yang dapat mencengkram telapak kaki dengan baik sehingga meminimalisir kemungkinan kaki bergeser didalam sepatu yang dapat menyebabkan cidera. MILLS REINF INTERCROSS adalah teknologi pada outsole sepatu football MILLS seperti pondasi / konstruksi menyilang yang terletak pada bagian MILLS TRX GRVTY+ adalah sistem stud/pul sepakbola MILLS. Didesain secara khusus dengan bentuk dan diletakan secara sistematis pada titik traksi yang sesuai. Teknologi ini dapat memberikan daya cengkram yang maksimal seperti mendapat grafiti tambahan, sehingga memungkingkan pemain dapat bermanufer dengan bebas dan tetap nyaman.</p>\r\n', 'produk1717915872.jpeg', 1, '2024-06-08 23:50:11'),
(58, 3, 'MILLS Sepatu Sepakbola Xyclops ACG MK II Prime FG White / Spectra. Green 9303601', 569000, '<p>MILLS Sepatu Sepakbola Xyclops ACG MK II Prime FG Category : Soccer FG Dirancang Untuk : Bermain sepak bola intesitas tinggi dengan karakter versatile dan mobile pemain yang ingin menaikan level kecepatan dan kontrol atas bola. Direkomendasikan untuk pemain dengan posisi: CF / WF / AMF / CMF Di lengkapi dengan Teknologi : MILLS ACG ACTIVE TOUCH adalah teknologi upper sepatu dengan merekayasa tekstur material sehingga menciptakan permukaan matrial yang dapat membantu mencengkram bola untuk menambah power, mengontrol dan mengatur arah bola. MILLS EXOSKIN adalah teknologi upper sepatu sintetik yang ringan, kuat, dan dapat memeluk / memberikan proteksi pada kaki secara maksimal. didesain untuk pemain yang memiliki mobilitas yang tinggi. MILLS TRX GRVTY+ adalah teknologi stud sepakbola MILLS. Didesain secara khusus dengan bentuk dan diletakan secara sistematis pada titik traksi yang sesuai. Teknologi ini dapat memberikan daya cengkram yang maksimal seperti mendapat gravitasi tambahan, sehingga memungkingkan pemain dapat bermanufer dengan bebas dan tetap nyaman.</p>\r\n', 'produk1717915972.jpeg', 1, '2024-06-08 23:52:52'),
(59, 3, 'MILLS Sepatu Sepakbola Astro Spartan MK Elite FG White / Gold / Navy 9301505', 899000, '<p>&nbsp;</p>\r\n\r\n<p>MILLS Sepatu Sepakbola Astro Spartan MK Prime FG Category : Soccer FG Sepatu soccer di Family ASTRO yang didesain dengan konsep futurism legacy, stylish / heritage. Sepatu ini sudah menggunakan material kulit premium pada area depan sehingga dapat mamaksimalkan kenyamanan pemain diatas lapangan. Sepatu ini dilengkapi sole dengan konfigurasi blade-stud (Untuk FG) cocok untuk karakter permainan yang mobile dan agile seperti MK. Rekomendasi Untuk Posisi : DMF, CMF , AMF Rekomendasi Lapangan : FG (Frime Ground) Di lengkapi dengan Teknologi : MILLS K-PRIME adalah aplikasi upper yang menggunakan material kulit sapi yang di rekonstruksi sehingga menyerupai kulit kangguru yang terkenal memiliki kekuatan, elastisitas, dan ﬁtting yang baik. Ditempatkan diarea upper sepatu untuk kenyamanan yang sempurna. MILLS AEROMESH X S.P. SKIN adalah teknologi upper sepatu berbahan material breathable mesh yang dikombinasikan dengan material TPU diperukaannya, menghasilkan upper sepatu yang ringan, memiliki ﬂeksibilitas yang baik, nyaman dan memberikan ﬁtting terbaik dikelasnya. MILLS High Density KNIT / HD KNIT adalah teknologi upper sepatu yang terbuat dari benang polyerser dan benang elastis yang dirajut sehingga menghasilkan material upper yang lembut kuat, dan dapat mengikuti bentuk kaki penggunanya, sehingga ﬁtting sepatu akan jauh lebih maksimal dan nyaman. MILLS High Density KNIT / HD KNIT adalah teknologi upper sepatu yang terbuat dari benang polyerser dan benang elastis yang dirajut sehingga menghasilkan material upper yang lembut kuat, dan dapat mengikuti bentuk kaki penggunanya, sehingga ﬁtting sepatu akan jauh lebih maksimal dan nyaman. MILLS REINF INTERCROSS adalah teknologi pada outsole sepatu football MILLS seperti pondasi / konstruksi menyilang yang terletak pada bagian tengah. teknologi ini menjaga agar sepatu tidak twisting atau menjaga kaki pemain agar tidak cidera dan memberikan kekuatan dan proteksi tambahan dibagian tumit hingga tengah sepatu. MILLS REINF INTERCROSS adalah teknologi pada outsole sepatu football MILLS seperti pondasi / konstruksi menyilang yang terletak pada bagian tengah. teknologi ini menjaga agar sepatu tidak twisting atau menjaga kaki pemain agar tidak cidera dan memberikan kekuatan dan proteksi tambahan dibagian tumit hingga tengah sepatu.</p>\r\n', 'produk1717916085.jpeg', 1, '2024-06-08 23:54:45'),
(60, 6, 'MILLS Sepatu Olahraga Treximo Saga V2 MK II White / Spectra Green / Black 9101208', 529000, '<p>MILLS TREXIMO SAGA V2 MK II Category: RUNNING Retail Price: 529,000 MILLS TREXIMO SAGA V2 MK II: TETAP PRODUKTIF BERLARI SAAT CUACA PANAS! MILLS Treximo Saga datang dengan material translucent yang mampu menjaga stabilitas udara di sekitar kaki. Membuatmu tak lagi ragu berolahraga di kala cuaca panas. DIRANCANG UNTUK: Aktivitas berlari lebih cepat, sehingga membutuhkan sepatu yang ringan. Sepatu ini digunakan untuk berlari di permukaan datar dengan jarak 5-10K. TRANSLUCENT mesh upper membuat Anda lebih siap untuk berlari di musim kemarau/panas. MILLS SEAMPRESS SKIN adalah teknologi yang memungkinan membuat konstruksi / dekorasi sepatu tanpa jahitan. berbahan dasar TPU yang kuat dan ringan. sehingga dapat memberikan konstruksi tambahan pada upper sepatu namun tidak mempengaruhi bobot dan elastisitasnya. MILLS APTIVE FOAM adalah teknologi outsole/midsole berbahan dasar campuran biji EVA, okisgen dan rubber yang dibuat dengan metode injection phylon. menghasilkan midsole yang kenyal dan dapat meredam getaran dengan baik. Selain itu sole menjadi Ringan, sangat fleksible dan memiliki elastisitas tinggi.</p>\r\n', 'produk1717916298.jpeg', 1, '2024-06-08 23:58:18'),
(61, 6, 'MILLS Sepatu Specter Black / White 9101406', 329000, '<p>&nbsp;</p>\r\n\r\n<p>MILLS Sepatu Running Specter Sebuah sepatu yang didesain untuk keperluan Serbaguna / Versatile, dengan didesain untuk keperluan serbaguna maka dibuat terlihat Simple tapi tidak menghilangkan kesan Sporty , Sepatu Running Specter juga dibuat untuk kebutuhan Performance dengan elastisitas dan ketahanan untuk mendukung pergerakan pemakainya karena adanya Teknologi : Upper Syntetic &amp; Mesh Teknologi yang diterapkan pada bagian upper sepatu yang dapat menberikan kenyamanan saat berjalan dan berlari, ringan dan lembut yang dapat mengikuti bentuk kaki agar semakin nyaman dan tentunya sangat ringan. Outsole Phylon Outsole dengan material phylon yang ringan dan kuat. Memberikan akselerasi dan traksi terbaik saat digunakan. Sepatu Running Specter memudahkan kalian menemukan sepatu Running yang dibuat Versatile, Simple dan Menunjang Performance.</p>\r\n', 'produk1717916412.jpeg', 1, '2024-06-09 00:00:12'),
(62, 6, 'MILLS Sepatu Treximo Omega Black/Black 9100113', 349000, '<p>&nbsp;</p>\r\n\r\n<p>TREXIMO &ndash; OMEGA Treximo Omega adalah Product Sepatu pertama dari kami yang dibuat 3 unsur yaitu, Sebuah sepatu yang didesain untuk keperluan Serbaguna / Versatile, dengan didesain untuk keperluan serbaguna maka Treximo Omega dibuat terlihat Simple tapi tidak menghilangkan kesan Sporty dan Gagah, Treximo Omega juga dibuat untuk kebutuhan Performance dengan elastisitas dan ketahanan untuk mendukung pergerakan pemakainya karena adanya Teknologi : Upper Syntetic &amp; Mesh Teknologi yang diterapkan pada bagian upper sepatu yang dapat menberikan kenyamanan saat berjalan dan berlari, ringan dan lembut yang dapat mengikuti bentuk kaki agar semakin nyaman dan tentunya sangat ringan. Outsole Phylon Outsole dengan material phylon yang ringan dan kuat. Memberikan akselerasi dan traksi terbaik saat digunakan. Treximo Omega memudahkan kalian menemukan sepatu Running yang dibuat Versatile, Simple dan Menunjang Performance.</p>\r\n', 'produk1717916506.jpeg', 1, '2024-06-09 00:01:46'),
(63, 6, 'MILLS Sepatu Specter Black / White 9101406', 329000, '<p>&nbsp;</p>\r\n\r\n<p>MILLS Sepatu Running Specter Sebuah sepatu yang didesain untuk keperluan Serbaguna / Versatile, dengan didesain untuk keperluan serbaguna maka dibuat terlihat Simple tapi tidak menghilangkan kesan Sporty , Sepatu Running Specter juga dibuat untuk kebutuhan Performance dengan elastisitas dan ketahanan untuk mendukung pergerakan pemakainya karena adanya Teknologi : Upper Syntetic &amp; Mesh Teknologi yang diterapkan pada bagian upper sepatu yang dapat menberikan kenyamanan saat berjalan dan berlari, ringan dan lembut yang dapat mengikuti bentuk kaki agar semakin nyaman dan tentunya sangat ringan. Outsole Phylon Outsole dengan material phylon yang ringan dan kuat. Memberikan akselerasi dan traksi terbaik saat digunakan. Sepatu Running Specter memudahkan kalian menemukan sepatu Running yang dibuat Versatile, Simple dan Menunjang Performance.</p>\r\n', 'produk1717916595.jpeg', 1, '2024-06-09 00:03:15');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tb_admin`
--
ALTER TABLE `tb_admin`
  ADD PRIMARY KEY (`admin_id`);

--
-- Indexes for table `tb_category`
--
ALTER TABLE `tb_category`
  ADD PRIMARY KEY (`category_id`);

--
-- Indexes for table `tb_product`
--
ALTER TABLE `tb_product`
  ADD PRIMARY KEY (`product_id`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tb_admin`
--
ALTER TABLE `tb_admin`
  MODIFY `admin_id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `tb_category`
--
ALTER TABLE `tb_category`
  MODIFY `category_id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `tb_product`
--
ALTER TABLE `tb_product`
  MODIFY `product_id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
